<!DOCTYPE html>
<html>
    <head>
        <link href="css/stylesheet.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script>
            jQuery(document).ready(function($) {
                $(".clickable-row").click(function() {
                    window.document.location = $(this).data("href");
                });
            });
        </script>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </head>
   <body><!-- background="./img/glowing-blue-circles-19043-1920x1200.jpg"-->
        <div>
            <header>
                <titel><img id="phpTitel" src="img/PHP-logo.svg.png" alt=""/> File Browser</titel>
            </header>
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="http://localhost/">
                                    <button type="button" class="btn btn-default btn-lg">
                                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
                                    </button>
                                </a>
                            </li>
                            <li>
                              <button form="file-form" type="submit" class="btn btn-default btn-lg">
                                    <span  class="glyphicon glyphicon-floppy-save" value="Save"/>Save
                              </button>
                            </li>
                            <li>
                                <div class="disabled">
                                    <input type="text" class="disabled" <?php if (isset($file)){ echo "$route / $file"; } else { echo "$route"; } ?>>
                                </div>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Made with <span class="caret"></span></a>
                                <ul class="dropdown-menu">       
                                    <li><a href="http://www.w3schools.com/html/ " target="_blank">Html</a></li>
                                    <li><a href="http://php.net/" target="_blank">Php</a></li>
                                    <li><a href="http://getbootstrap.com/" target="_blank">Bootstrap</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row">
                    <?php if (isset($file))  { ?>
                        <div class="col-md-7 col-lg-5">
                    <?php } else { ?>
                        <div class="col-md-12">
                    <?php } ?>
                    <table class="table table-hover" >
                        <tr>
                            <th>Name</th>
                            <th>File Size</th>
                            <th>Last modified</th>
                            <th>Writeable</th>
                        </tr>
                        <?php foreach($itemLinks as $item => $properties){ ?>
                            <tr class='clickable-row' data-href='?route=<?php echo $properties['link'] ?>'>
                                <td>
                                    <?php echo $item ?>
                                </td>
                                <td>
                                    <?php if ($properties['is_file']) { ?>
                                        <?php echo $properties['size'] ?>
                                    <?php } else { ?>
                                        -
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if ($properties['is_file']) { ?>
                                        <?php echo $properties['last_modified'] ?>
                                    <?php } else { ?>
                                        -
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if ($properties['is_file']) { ?>
                                        <?php echo $properties['is_writeable'] ?>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php }  ?>
                    </table>
                </div>
                    <?php if (isset($file))  { ?>
                    <div class="col-md-5 col-lg-7">
                        <?php if ($fileIsText) { ?>
                            <form id="file-form" method="post" action="?route=<?php echo "$route/$file" ?>">
                                <textarea rows="18" class="form-control" name="file-contents" width="100%" ><?php echo $readHtmlChars ?></textarea>
                            </form>
                        <?php } ?>
                        <?php if ($fileIsImage) { ?>
                            <img src="<?php echo $route . '/' . $file ?>"/>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </body>
</html> 
                            